[env]
DOCKER_IMAGE = "quay.io/megumish/${CARGO_MAKE_CRATE_NAME}"
OPERATOR_NS = "tekito-operator"

[tasks.clean_all_manifests]
command = "rm"
args = ["-rf", "./target/config"]

[tasks.generate_all_manifests]
run_task = [ 
  { name = ["generate_namespaces", "generate_crds", "generate_managers", "generate_rbacs"] }
]

[tasks.generate_namespaces]
command = "cargo"
args = ["run", "--bin", "generate_namespaces"]

[tasks.generate_crds]
command = "cargo"
args = ["run", "--bin", "generate_crds"]

[tasks.generate_managers]
command = "cargo"
args = ["run", "--bin", "generate_managers"]

[tasks.generate_rbacs]
command = "cargo"
args = ["run", "--bin", "generate_rbacs"]

[tasks.docker_build]
command = "docker"
args = ["build", "-t", "${DOCKER_IMAGE}:v${CARGO_MAKE_CRATE_VERSION}", "."]

[tasks.docker_push]
command = "docker"
args = ["push", "${DOCKER_IMAGE}:v${CARGO_MAKE_CRATE_VERSION}"]

[tasks.create_namespace]
command = "kubectl"
args = ["create", "namespace", "${OPERATOR_NS}"]

[tasks.apply_all_manifests]
run_task = [
  { name = ["apply_namespaces", "apply_crds", "apply_managers", "apply_rbacs"] }
]

[tasks.apply_namespaces]
command = "kubectl"
args = ["apply", "-f", "./target/config/namespaces"]

[tasks.apply_crds]
command = "kubectl"
args = ["apply", "-f", "./target/config/crds"]

[tasks.apply_managers]
command = "kubectl"
args = ["apply", "-f", "./target/config/managers"]

[tasks.apply_rbacs]
command = "kubectl"
args = ["apply", "-f", "./target/config/rbacs"]

[tasks.delete_all_manifests]
run_task = [
  { name = ["delete_crds", "delete_managers", "delete_rbacs", "delete_namespaces"] }
]

[tasks.delete_namespaces]
command = "kubectl"
args = ["delete", "-f", "./target/config/namespaces"]

[tasks.delete_crds]
command = "kubectl"
args = ["delete", "-f", "./target/config/crds"]

[tasks.delete_managers]
command = "kubectl"
args = ["delete", "-f", "./target/config/managers"]

[tasks.delete_rbacs]
command = "kubectl"
args = ["delete", "-f", "./target/config/rbacs"]

[tasks.build_and_push_operator]
run_task = [
  { name = [
    "docker_build",
    "docker_push",
  ] }
]

[tasks.install]
run_task = [
  { name = [
    "generate_all_manifests",
    "apply_all_manifests",
  ] }
]

[tasks.uninstall]
run_task = [
  { name = [
    "delete_all_manifests",
  ] }
]